### ISSUE TITLE
Markdown parser gobbles up inline formatting

### ISSUE THREAD

**Issue by eddieantonio** [tldr-pages/tldr-node-client#51] opened 2015-12-31 07:50 UTC
Whenever description text is _emphasized_ or **bolded** for effect, it disappears in the Node client output.

The following...

```markdown
- Limit results to strings at least *length* characters long

`strings -n {{length}} {{file}}`
```

...is rendered as:

<img width="492" alt="captura de pantalla 2015-12-31 a las 12 46 30 a m" src="https://cloud.githubusercontent.com/assets/2294397/12062335/f895089e-af57-11e5-8bce-a8822855c9ba.png">

(Compare against the [web client](http://www.ostera.io/tldr.jsx/#/strings).)

**Note**: the intention in this page is that *length* is a placeholder mentioned in the following example. Perhaps it use should the curly-brace mark-up instead; however, the curly-brace placeholders are only highlighted in the example code block:

```markdown
- Limit results to strings at least `{{length}}` characters long

`strings -n {{length}} {{file}}`
```

<img width="497" alt="captura de pantalla 2015-12-31 a las 12 41 15 a m" src="https://cloud.githubusercontent.com/assets/2294397/12062330/d3015a24-af57-11e5-9d57-018ce84128df.png">

**Comment by igorshubovych** [comment] 2016-01-09 17:57
It does not need to show it anyhow. Parser parse according to format described in [Contribution Guidelines](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md#markdown-format).

**Comment by agnivade** [comment] 2016-10-04 05:52
Closing this as its a duplicate of #77. Lets continue the conversation there.

**Closed by agnivade** 2016-10-04 05:52 UTC
Labels: duplicate
