### ISSUE TITLE
vim.md renders incorrectly

### ISSUE THREAD

**Issue by iliakonnov** [tldr-pages/tldr-node-client#139] opened 2017-02-17 17:31 UTC
## Expected behaviour
tldr client should display `<Esc>i`, `<Esc>u`, `<Esc>/search_pattern<Enter>` (`search_pattern` underlined)

## Actual behaviour
tldr client displays `P`, `N`, `$`

On screenshot I have highlited difference between markdown file (yellow) and tldr output (orange).
![bug](https://cloud.githubusercontent.com/assets/9402179/23075958/82d20c58-f54f-11e6-9108-62dee6fcb35d.png)

## Environment
- Operating system - Linux, Ubuntu 16.04
- NodeJS version - v4.2.6

**Comment by agnivade** [comment] 2017-02-17 17:43
oh wow. Indeed that is some weird shit going on.

**Comment by agnivade** [comment] 2017-03-03 04:54
It was a dupe of #136. Published a new release to npm.

**Closed by agnivade** 2017-03-03 04:54 UTC
Labels: bug
