### ISSUE TITLE
Search for "editor" does not find page "nano"

### ISSUE THREAD

**Issue by MDecker-MobileComputing** [tldr-pages/tldr-node-client#363] opened 2021-10-26 15:27 UTC
## Expected behavior
When I execute the command `tldr --search editor`, then the result list should contain the entry "nano", because the text of this page contains the word "editor".

First sentence on this page contains word "editor" (see [here](https://github.com/tldr-pages/tldr/blob/main/pages/common/nano.md) for full text of page):
> Simple, easy to use command-line text editor. 

## Actual behavior
The list of search results does NOT contain "nano":

```
$ tldr --search editor
Searching for: editor

    $ sensible-editor
    $ qcp
    $ lambo
    $ gh-config
    $ fc
    $ qmv
    $ pueue-edit
    $ micro
    $ git-authors
    $ helix
```

The cause for this issue might be that in page "nano" the word "editor" is at the end of an sentence (i.e. "editor."), and therefore the  tokenizer for indexing all pages does not recognize this word.

Might be related to [issue 193](https://github.com/tldr-pages/tldr-node-client/issues/193).

## Environment
- Operating system: Linux (Raspbian 10)
- Node.js version: 12.22.7
- tldr-node-client: 3.3.7

**Comment by agnivade** [comment] 2022-09-04 07:54
Yeah looks like duplicate of #193. In general search is unmaintained in this tool. The person who originally contributed it, is unresponsive. If anyone wants to look at the bug, that'll be great.

**Closed by agnivade** 2022-09-04 07:54 UTC
Labels: bug
